services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_files:/var/www/html
    restart: on-failure
    healthcheck:
      test: ["CMD", "test", "-f", "/var/www/html/wp-config.php"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    env_file: .env
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_files:/var/www/html
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rlane/data/mariadb

  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rlane/data/wordpress
