services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_files:/var/www/html
    restart: on-failure
    healthcheck:
      test: ["CMD", "test", "-f", "/var/www/html/wp-config.php"] # Check if wp-config.php exists
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    env_file: .env
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_files:/var/www/html
      - static_files:/var/www/static
    restart: on-failure

  staticwebsite:
    build:
      context: ./requirements/staticwebsite
    container_name: staticwebsite
    volumes:
      - static_files:/var/www/static
    networks:
      - inception
    restart: on-failure

  redis:
    build:
      context: ./requirements/redis
    container_name: redis
    networks:
      - inception
    volumes:
      - redis_data:/var/lib/redis
    restart: always

  ftp:
    build:
      context: ./requirements/ftp
    container_name: ftp
    env_file: .env
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
    networks:
      - inception
    volumes:
      - wordpress_files:/var/www/html
    ports:
      - "21:21"
      - "21000-21001:21000-21001"
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  wordpress_files:
    driver: local
  static_files:
    driver: local
  redis_data:
    driver: local
