services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: on-failure

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_files:/var/www/html
    restart: on-failure

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_files:/var/www/html
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rlane/data/mariadb
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rlane/data/wordpress
