services:
  nginx:
    build: ./srcs/requirements/nginx
    ports:
      - "${HTTPS_PORT}:443"
    volumes:
      - ./srcs/requirements/nginx/conf:/etc/nginx/conf.d
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    build: ./srcs/requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306 # use the mariadb port and name
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE} #values from .env file
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - "${WORDPRESS_PORT}"
    networks:
      - inception

  mariadb:
    build: ./srcs/requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - inception

volumes:
  wordpress_data:
  mariadb_data:

networks:
  inception:
